### ISSUE TITLE
Opcode 看起来不对

### ISSUE THREAD

**Issue by woodnaonly** [NukoOoOoOoO/FFXIV-OpcoeFinder#1]
EffectResult
ActorGauge
对比
https://github.com/zhyupe/ffxiv-opcode-worker/blob/master/cn-opcodes.csv

**Comment by Nukoooo** [comment]
- EffectResult是因为没法处理多个结果而只显示了一个.但它有一个类似PreProcess的function,里面有opcode,之后会用这个来获取EffectResult的opcode

- ActorGauge似乎也是一样的,但Preprocess的function没法生成signature,目前还没有想到好的解决办法

会尽快修复,感谢指出!

**Comment by Nukoooo** [comment]
最新的commit修复了这个问题(之前一直在忙别的，没啥动力修)
