### ISSUE TITLE
关于sig

### ISSUE THREAD

**Issue by tssailzz8** [NukoOoOoOoO/FFXIV-OpcoeFinder#2]
这些sig都是怎样去寻找到的

**Comment by Nukoooo** [comment]
在IDA里找到[这个function](https://github.com/ottercorp/Dalamud/blob/master/Dalamud/Game/Network/GameNetworkAddressResolver.cs#L23)，然后反编译得出伪代码。这个function里有一个switch statement，然后有很多cases。而cases的值就是对应的opcode。config里的opcode都是从这个[repo](https://github.com/zhyupe/ffxiv-opcode-worker)里拿的。

如果有人在看这个issue的话，目前获取EventPlay的Opcode方法不稳定，之后会更新下
